config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations', passwords: 'admins/passwords', mailer: 'admins/mailer' }
  resources :widgets

  root 'welcome#index'
  
  get 'certify' => 'welcome#certify_me'
  post 'certified' => 'welcome#certified'

  resources :articles do
    resources :figures do
    end
  end

end

app/models/Tag.rb
class Tag < ActiveRecord::Base
  has_many :articles, through: :article_tags
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_one :auth_code
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :article_tags
  has_many :figures, dependent: :destroy
  has_many :sections, dependent: :destroy
  has_many :tags, :through => :article_tags
  
  has_many :references, through: :article_references
  belongs_to :admin
  belongs_to :category
  scope :visible, -> { where(visible: true) }
end

app/models/article_presenter.rb
require 'delegate'

class ArticlePresenter < SimpleDelegator
  extend ActiveModel::Naming

  def to_model
    self
  end

  def intro
    @intro = model.main_content[0..100]
  end

  def welcome_image
    model.figures[0].avatar.url(:small)
  end
  #returns a reference to the object that the method calls are being delegated to
  def model
    __getobj__
  end
end

app/models/article_reference.rb
class ArticleReference < ActiveRecord::Base
  belongs_to :article
  belongs_to :reference
end

app/models/article_tag.rb
class ArticleTag < ActiveRecord::Base
  belongs_to :article
  belongs_to :tag
end

app/models/auth_code.rb
class AuthCode < ActiveRecord::Base
  belongs_to :admin

  def uncertify!
    self.code = nil
    save!
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true
end

app/models/figure.rb
class Figure < ActiveRecord::Base
  has_attached_file :avatar, styles: { large: "2200x500#", medium: "990x350#", small: "150x150!"}, default_url: "images/:style/missing.png"
  validates_attachment :avatar, presence: true,
                        content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  has_many :articles, through: :article_references
end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :certify_admin!, :except => [:index, :show]
  respond_to :html, :json

  def new
    @article = Article.new
  end

  def edit
    if admin_authorized?
      @article = get_article
      @figures = @article.figures
    else
      warn_logout!
    end
  end

  def create
    @article = Article.new(article_params.merge(admin_id: current_admin.id))
    if @article.save
      redirect_to articles_url
    else
      render new
    end
  end

  def update
    if admin_authorized?
      @article = get_article
      if @article.update_attributes(article_params)
        redirect_to article_url(@article)
      else
        render 'edit'
      end
    else
      warn_logout!
    end
  end

  def index
    if super_admin?
      @articles = Article.all.map { |a| ArticlePresenter.new(a) }
    else
      @articles = Article.visible.map { |a| ArticlePresenter.new(a) }
    end
    respond_with(@articles)
  end

  def show
    @article = Article.find(params[:id])
    if super_admin? || @article.visible
      @figures = @article.figures.order(:order_num)
      render 'show.html.erb'
    else
      redirect_to articles_url
    end
  end

  def destroy
  end

  private
  def article_params
    params.require(:article).permit(:title,:sub_title,:main_content,:posted_on,:visible)
  end

  def get_article
    article ||= Article.find(params[:id])
  end
  
  def admin_authorized?
    #is the admin who created this article?
    get_article.admin_id == current_admin.id
  end

  def certify_admin!
    authenticate_admin!
    #if current_admin is cerified return true otherwise signout current_admin
    current_admin.certified || (signout current_admin)
  end

  def warn_logout!
    flash[:notice] = "DONT DO THAT; You are editing someone else article???"
    current_admin.auth_code.uncertify!
    signout current_admin
  end

  def super_admin?
    (current_admin && current_admin.email == 'sowju19@gmail.com')
  end
end

app/controllers/auth_codes_controller.rb
class AuthCodesController < ApplicationController
  before_action :authenticate_admin!
  require 'digest/md5'

  def new
    if super_admin?
      @all_admins = Admin.all.map {|a| [a.name,a.id]}
      @auth_code = AuthCode.new
    end
  end

  def create
    if super_admin?
      @code = generate_code
      @auth_code = AuthCode.new(code: @code, admin_id: params[:certify_admin_id])
      if @auth_code.save?
        @certified_admin = Admin.find(params[:certify_admin_id])
        render template: auth_codes/show_code
      else
        flash[:notice] = "something went wrong in code generation"
        render new
      end
    end
  end

  private

  def super_admin?
    (current_admin.email == 'sowju19@gmail.com')
  end

  def generate_code
    my_code = Digest::MD5.hexdigest Time.now.to_i.to_s
    my_code[2..10]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/figures_controller.rb
class FiguresController < ApplicationController
  def new
    @article = Article.find(params[:article_id])
    @existing_figures = @article.figures
    @figure = Figure.new(article_id: @article_id)
  end

  def create
    @article = Article.find(params[:article_id])
    @figure = Figure.new(figure_params)
    @figure.article_id = params[:article_id]
    if @figure.save
      redirect_to article_url(@article)
    else
      render new
    end
  end

  def index
  end

  def edit
  end

  def delete
  end

  def update
  end

  def show
  end

  private

  def figure_params
    params.require(:figure).permit(:fig_name, :order_num, :avatar, :article_id)
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def index
  end

  def destroy
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def index
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tech_articles = Article.visible.last(8)
    @tech_articles = @tech_articles.map { |a| ArticlePresenter.new(a) }
  end

  def certify_me
    authenticate_admin!
    @admin = current_admin
  end

  def certified
    authenticate_admin!
    if params[:my_code] && (current_admin.auth_code.try(:code) == params[:my_code])
      current_admin.certified = true
      current_admin.save
      flash[:notice] = "Authorized to create Articles"
      redirect_to :root
    else
      flash[:error] = "Authorization code invalid"
      redirect_to :root
    end
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @widgets = Widget.all
    respond_with(@widgets)
  end

  def show
    respond_with(@widget)
  end

  def new
    @widget = Widget.new
    respond_with(@widget)
  end

  def edit
  end

  def create
    @widget = Widget.new(widget_params)
    @widget.save
    respond_with(@widget)
  end

  def update
    @widget.update(widget_params)
    respond_with(@widget)
  end

  def destroy
    @widget.destroy
    respond_with(@widget)
  end

  private
    def set_widget
      @widget = Widget.find(params[:id])
    end

    def widget_params
      params.require(:widget).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title %>
   <br>
   <%= f.label :sub_title %>
   <%= f.text_field :sub_title %>
   <br>
   <%= f.label :main_content %>
   <%= f.text_area :main_content, size: "200x20" %>
   <br>
   <%= f.label :posted_on %>
   <%= f.date_select :posted_on %>
   <br>
   <%= f.label :visible %>
   <%= f.select :visible, [[true,true],[false,false]], include_blank: false %>
   <br>
   <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>
<h1>Existing Images</h1>
<% @figures.each do |f| %>
  <%= image_tag f.avatar.url(:small) %>
<% end %>
<%= link_to 'Add Image', new_article_figure_path(@article.id) %>

app/views/articles/index.html.erb
<div id="index_page">
  <% 0.upto(@articles.length/8 + 1) do |i| %>
    <% if i % 2 == 0 %>
    <section class="row_styling clearfix">
      <% if my_article = @articles[i*8] %>
        <article class="unit col15">
          <a href="<%= article_url(my_article) %>">
            <img class="blog_img" src="assets/personal-1.jpg"  height="400px">
            <h1><%= my_article.title %></h1>
            <p><%= my_article.intro %>...</p>
          </a>
        </article>
      <% end %>
      <section class=" unit col2of5">
        <section class="clearfix">
          <% if my_article = @articles[i*8 + 1] %>
          <article class="unit col2of5">
            <a href="<%= article_url(my_article) %>">
              <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
              <h1><%= my_article.title %></h1>
              <p><%= my_article.intro %>...</p>
            </a>
          </article>
          <% end %>
          <% if my_article = @articles[i*8 + 2] %>
          <article class="unit col2of5 ">
            <a href="<%= article_url(my_article) %>">
              <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
              <h1><%= my_article.title %></h1>
              <p><%= my_article.intro %>...</p>
            </a>
          </article>
          <% end %>
        </section>
        <section class="clearfix">
          <% if my_article = @articles[i*8 + 3] %>
            <article class="unit col2of5">
              <a href="<%= article_url(my_article) %>">
                <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
                <h1><%= my_article.title %></h1>
                <p><%= my_article.intro %>...</p>
              </a>
            </article>
          <% end %>
          <% if my_article = @articles[i*8 + 4] %>
            <article class="unit col2of5 ">
              <a href="<%= article_url(my_article) %>">
                <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
                <h1><%= my_article.title %></h1>
                <p><%= my_article.intro %>...</p>
              </a>
            </article>
          <% end %>
        </section>
      </section>
      <% if my_article = @articles[i*8 + 5] %>
      <article class="unit col15">
        <a href="<%= article_url(my_article) %>">
          <img class="blog_img" src="assets/personal-1.jpg"  height="400px">
          <h1><%= my_article.title %></h1>
          <p><%= my_article.intro %>...</p>
        </a>
      </article>
      <% end %>
      <section class="unit col1of5">
        <% if my_article = @articles[i*8 + 6] %>
        <article>
          <a href="<%= article_url(my_article) %>">
            <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
            <h1><%= my_article.title %></h1>
            <p><%= my_article.intro %>...</p>
          </a>
        </article>
        <% end %>
        <% if my_article = @articles[i*8 + 7] %>
        <article>
          <a href="<%= article_url(my_article) %>">
            <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
            <h1><%= my_article.title %></h1>
            <p><%= my_article.intro %>...</p>
          </a>
        </article>
        <% end %>
      </section>
    </section>
    <% else %>
    <section class=" unit col2of5">
      <section class="clearfix">
        <% if my_article = @articles[i*8] %>
        <article class="unit col2of5">
          <a href="<%= article_url(my_article) %>">
            <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
            <h1><%= my_article.title %></h1>
            <p><%= my_article.intro %>...</p>
          </a>
        </article>
        <% end %>
        <% if my_article = @articles[i*8 + 1] %>
        <article class="unit col2of5 ">
          <a href="<%= article_url(my_article) %>">
            <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
            <h1><%= my_article.title %></h1>
            <p><%= my_article.intro %>...</p>
          </a>
        </article>
        <% end %>
      </section>
      <section class="clearfix">
        <% if my_article = @articles[i*8 + 2] %>
        <article class="unit col2of5">
          <a href="<%= article_url(my_article) %>">
            <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
            <h1><%= my_article.title %></h1>
            <p><%= my_article.intro %>...</p>
          </a>
        </article>
        <% end %>
        <% if my_article = @articles[i*8 + 3] %>
        <article class="unit col2of5 ">
          <a href="<%= article_url(my_article) %>">
            <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
            <h1><%= my_article.title %></h1>
            <p><%= my_article.intro %>...</p>
          </a>
        </article>
        <% end %>
      </section>
    </section>
    <% if my_article = @articles[i*8 + 4] %>
    <article class="unit col15">
      <a href="<%= article_url(my_article) %>">
        <img class="blog_img" src="assets/personal-1.jpg"  height="400px">
        <h1><%= my_article.title %></h1>
        <p><%= my_article.intro %>...</p>
      </a>
    </article>
    <% end %>
    <section class="unit col2of5">
      <% if my_article = @articles[i*8 + 5] %>
      <article>
        <a href="<%= article_url(my_article) %>">
          <img class="blog_img" src="assets/personal-1.jpg"  height="150px">
          <h1><%= my_article.title %></h1>
          <p><%= my_article.intro %>...</p>
        </a>
      </article>
       <% end %>
      <section class="clearfix">
        <% if my_article = @articles[i*8 + 6] %>
        <article class="unit col2of5">
          <a href="<%= article_url(my_article) %>">
            <img class="blog_img" src="assets/personal-1.jpg"  height="300px">
            <h1><%= my_article.title %></h1>
            <p><%= my_article.intro %>...</p>
          </a>
        </article>
        <% end %>
        <% if my_article = @articles[i*8 + 7] %>
        <article class="unit col2of5">
          <a href="<%= article_url(my_article) %>">
            <img class="blog_img" src="assets/personal-1.jpg"  height="300px">
            <h1><%= my_article.title %></h1>
            <p><%= my_article.intro %>...</p>
          </a>
        </article>
        <% end %>
      </section>
    </section>
    <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<% if current_admin %>
  <%= link_to 'Signout', {controller: 'admins/sessions', action: 'destroy', id: current_admin.id}, method: :delete %>
<% end %>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="article_show">
  <ul>
    <% @article.tags.each do |t| %>
      <li><%= t.name %></li>
    <% end %>
  </ul>
  <article>
    <h1><%= @article.title %></h1>
    <h2><%= @article.sub_title %></h1>
    <figure><%= image_tag @figures[0].avatar.url(:medium) %></figure>
    <p class="center"><span><%= @article.posted_on.strftime("%B %e, %Y") %>&nbsp&nbsp/ <span>Sowjanya M</span</p>
    <a class="twitter-share-button"
    href="https://twitter.com/share"
    data-size="large"
    data-text="<%= @article.twitter_share_text %>"
    data-url="https://dev.twitter.com/web/tweet-button"
    data-hashtags="example,demo">
  Tweet
  </a>
    <p><%= @article.main_content %></p>
  </article>
</div>

app/views/auth_codes/show_code.html.erb
<p>The Auth code for admin <%= @certified_admin.name %> is <%= @authcode.code %></p>

app/views/figures/_form.html.erb
<%= form_for [@article, @figure] do |f| %>
  <div class="form-row">
    <%= f.label :fig_name %>
    <%= f.text_field :fig_name %>
  </div>
  <div class="form-row">
    <%= f.label :order_num %>
    <%= f.text_field :order_num %>
  </div>
  <div class="form row">
    <%= f.file_field :avatar %>
  </div>
  <div class="form row">
    <%= f.submit %>
  </div>

<% end %>

app/views/figures/new.html.erb
<%= render 'form' %>